name: remote_ip_camera
description: Camera IP addon for remote ui package
version: 1.0.1
author: jaumard <jimmy.aumard@gmail.com>
homepage: https://github.com/jaumard/remote_ui/tree/master/packages/remote_ip_camera

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter_mjpeg: ^1.2.2
  flutter_hooks: ^0.6.0
  remote_ui: ^0.0.5
    ##path: '../remote_ui'
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
