name: remote_image_button
description: Image button addon for remote ui package
version: 0.0.2
author: jaumard <jimmy.aumard@gmail.com>
homepage: https://github.com/jaumard/remote_ui/tree/master/packages/remote_color_picker

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_svg: ^0.14.0
  flutter_hooks: ^0.6.0
  remote_ui: ^0.0.4
    ##path: '../remote_ui'
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
